config/routes.rb
###############################################################################
# Copyright 2012-2013 inBloom, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

LRMI::Application.routes.draw do

  # use a real resource
  resources :tagger, :only => [ :index, :save_draft, :save_export, :save_remote ] do
    collection do
      post :load_history,   :path => "/load_history",   :constraints => { :format => /json/ }
      post :load_drafts,    :path => "/load_drafts",    :constraints => { :format => /json/ }
      post :save_draft,     :path => "/save_draft",     :constraints => { :format => /json/ }
      post :save_export,    :path => "/save_export",    :constraints => { :format => /json/ }
      post :save_remote,    :path => "/save_remote",    :constraints => { :format => /json/ }
      post :reset_resource, :path => "/reset_resource", :constraints => { :format => /json/ }
      get :test_image_upload, :path => "/test_upload"
      post :add_image,      :path => "/add_image"
    end
  end
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  # Until we get the products united, just forward to tagger code
  root :to => 'tagger#index'

end

app/controllers/tagger_controller.rb
###############################################################################
# Copyright 2012-2013 inBloom, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

class TaggerController < ApplicationController

  def index
  end

  # Load the items list into the UI
  def load_drafts
    # The object we return to the UI, if any
    response = {}
    # Get our tags
    tags = Tag.where(:user_id => session[:user_id], :published => false).order("updated_at asc")
    tags.each_with_index do |tag,index|
      key = "itemTag"+index.to_s
      response[key] = ActiveSupport::JSON.decode(tag[:data])
    end

    respond_to do |format|
      format.json { render json: response }
    end
  end

  # Load the historical items into the UI
  def load_history
    # The object we return to the UI, if any
    response = {}
    # Get historical tags
    tags = Tag.where(:user_id => session[:user_id], :published => true).order("updated_at desc")
    tags.each_with_index do |tag,index|
      key = "historicalTag"+index.to_s
      response[key] = ActiveSupport::JSON.decode(tag[:data])
    end

    respond_to do |format|
      format.json { render json: response }
    end
  end

  # reset the requested resource
  def reset_resource
    found_tag = Tag.find_by_uuid params['uuid']
    if found_tag.present?
      found_tag.published = false
      found_tag.save();
    end

    respond_to do |format|
      format.json { head :no_content }
    end

  end

  # Saves a string to a file named filename on a user's machine
  def save_export
    send_data("#{params[:data]}", :filename => "#{params[:filename]}")
  end

  # Saves a json formatted string to the db, then formats and sends to LRI
  def save_draft
    # Parse through incoming tags array and create a tag for each
    tags = ActiveSupport::JSON.decode(params[:content])
    # Save those tags baby
    response = save_tags_state tags
    # Remove any tags that were deleted from the UI
    remove_deleted_tags tags

    respond_to do |format|
      format.json { render json: response }
    end
  end

  # Save the data to a remote thingy out in the world. Yes I said thingy!
  def save_remote
    # Parse through incoming tags array and create a tag for each
    json_tags = ActiveSupport::JSON.decode(params[:content])
    # Working array of tags
    tags = []
    # Break out the tags from the sent parsed json hash
    # And check to see if there is a UUID, if not set one.
    json_tags.each {|h|
      tmpTag = h[1].clone
      unless tmpTag['uuid'].present?
        tmpTag['uuid'] ||= SecureRandom.uuid
      end
      tags << tmpTag
    }
    # Choose which adaptor to use and publish those suckers
    case params[:remote]
#      when 'LRI'
#        errors = LriHelper::publish tags, current_user
      when 'LR'
        errors = LrHelper::publish tags, current_user
    end

    # TODO Eventually I need to only error those tags that didn't save, and set published the ones that did actually publish
    # If we have no errors, then go ahead and mark tags as published..etc..
    if errors.empty?
      # Save those tags baby
      save_tags_state json_tags, true

      # The object we return to the UI, if any
      response = {}
      # Get all the draft tags and send those to the ui
      tags = Tag.where(:user_id => session[:user_id], :published => false).order("updated_at asc")
      tags.each_with_index do |tag,index|
        key = "itemTag"+index.to_s
        response[key] = ActiveSupport::JSON.decode(tag[:data])
      end
    end

    respond_to do |format|
      if errors.empty?
        format.json { render json: response }
      else
        format.json { render status: 500, json: errors }
      end
    end
  end

  # Adds image to media server
  def add_image
#    if current_user.present?
      if params[:tag][:image].present?
        img = Image.new
        img.image = params[:tag][:image]
        img.save!
        # @todo: send img.image back to view
        # @todo: delete image from db asap
      end
#    end

    respond_to do |format|
      if img.present?
        format.json { render json: img }
      else
        format.json { render status: 500, json: 'Something went wrong'}
      end
    end
  end

  private

  # Its possible to need to save the tags from multiple places so lets extract this
  # out into a function of it's own for others to use.. share and share-a-like!
  def save_tags_state tags, publish = false
    # Dont do this if there is no user
    if current_user.present?
      # The object we return to the UI, if any
      response = {}
      tags.each do |keyValue|
        # This is the tag, 0 is the id in the UI which is meaningless
        tag = keyValue[1]
        # Remove the ID as it doesn't mean anything and is only used by the UI for internal stuff (if at all)
        tag.delete('id')
        # if we have a UUID then we must save to that!
        unless tag['uuid'].present?
          # Generate a UUID for this item that will be used when sent to the LRI or any server out in the world.
          # This is unique to this tag and its history and could come from the client
          tag['uuid'] ||= SecureRandom.uuid
        end
        # This tag has a UUID so we need to load it first
        found_tag = Tag.find_by_uuid tag['uuid']
        if found_tag.present?
          found_tag.user_id = session[:user_id]
          found_tag.data = tag.to_json
          found_tag.published = publish
          found_tag.save()
        else
          # Create each tag in the database
          Tag.create(
              :user_id => current_user.id,
              :uuid => tag['uuid'],
              :data => tag.to_json,
              :published => publish
          )
        end
        # Rebuild tags object for the UI
        response[keyValue[0]]= tag
      end if tags.present?

      response
    end

  end

  # Go through the list of tags the UI expects to be loaded on refresh and leave those.. remove the others.
  # without this if you delete a tag from the ui, save and reload the page it doesn't know to remove the deleted tag
  # as the save state function only saves to the tags already there or adds new ones.. doesn't know to remove.
  def remove_deleted_tags tags
    excluding = tags.map{|t| t[1]['uuid'] }
    if excluding.count == 0
      user_tags = Tag.where(:user_id => session[:user_id], :published => false).find(:all)
    else
      user_tags = Tag.where(:user_id => session[:user_id], :published => false).find(:all, :conditions => ['uuid not in (?)', excluding])
    end
    user_tags.each do |tag|
      tag.destroy
    end
  end

end

app/helpers/tagger_helper.rb
###############################################################################
# Copyright 2012-2013 inBloom, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

module TaggerHelper
end

app/views/tagger/modals/_alignment_modal.html.erb
<div id="alignmentsModal" class="modal hide fade bigModal">
  <div class="modal-header">
    <a onClick="$('#alignmentsModal').modal('hide');" class="close">&times;</a>
    <h3>Add Education Alignment</h3>
  </div>
  <div class="modal-body">

    <input type="hidden" id="itemGUID">
    <table cellspacing='2' cellpadding='5' class="table-condensed" >
      <tr>
        <td style="text-align:left;">
          <label class="control-label" for="educationalAlignment">Educational Alignment</label>
          <select class="input-xlarge required" id="educationalAlignment">
            <option selected="selected" value='Common Core State Standards'>Common Core State Standards</option>
          </select>
        </td>
        <td style="text-align:left;">
          <label class="control-label" for="alignmentType">Alignment Type</label>
          <select class="input-xlarge required" id="alignmentType">
            <option>Alignment Type...</option>
            <option value='assesses'>Assesses</option>
            <option value='teaches'>Teaches</option>
            <option value='requires'>Requires</option>
            <option value='' disabled='disabled' style='color:#ccc;'>TextComplexity</option>
            <option value='' disabled='disabled' style='color:#ccc;'>ReadingLevel</option>
            <option value='' disabled='disabled' style='color:#ccc;'>EducationalSubject</option>
            <option value='' disabled='disabled' style='color:#ccc;'>EducationLevel</option>

          </select>
        </td>
      </tr>
      <tr>
        <td style="text-align:left;">
          <label class="control-label" for="dotNotation">Dot Notation</label>
          <input type="text" class="input-xlarge required" id="dotNotation" placeholder='Dot Notation'>
        </td>
        <td style="text-align:left;">
          <label class="control-label" for="itemURL">Item URL</label>
          <input type="text" class="input-xlarge required" id="itemURL" placeholder='Item URL' readonly="readonly">
        </td>
      </tr>
      <tr>
        <td style="text-align:left;" colspan='2'>
          <label class="control-label" for="description">Description</label>
          <textarea type="text" class="textarea-xxlarge required" id="description" rows="3" readonly="readonly"></textarea>

          <!-- button class="btn btn-mini btn-warning disabled" id="deleteButton"><i class="icon-remove"></i> Delete</button -->

        </td>
      </tr>
    </table>

  </div>
  <div class="modal-footer">
    <button class="btn btn-success" id="addButton" disabled="disabled"><i class="icon-tag"></i> Add Alignment to Session</button>
    <a onClick="$('#alignmentsModal').modal('hide');" class="btn">Cancel</a>
  </div>
</div>

app/views/tagger/modals/_delete_modal.html.erb
<div id="deleteModal" class="modal hide fade">
  <div class="modal-header">
    <a onclick="$('#deleteModal').modal('hide'); return false;" class="close">&times;</a>
    <h3>Delete Resource</h3>
  </div>
  <div class="modal-body">
    <p>You're about to delete a local resource, this can't be undone.</p>
    <p>Are you sure?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-danger">Delete Resource</a>
    <a onclick="$('#deleteModal').modal('hide'); return false;" class="btn">Cancel</a>
  </div>
</div>

app/views/tagger/modals/_load_modal.html.erb
<div class="modal hide fade" id="loadModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" id="closeModalButton">X</button>
    <h3>Load A CSV Template</h3>
  </div>
  <div class="modal-body">
    <p>If you have utilized the LRMI CSV Template, you may select it from your local folder. The file must be in CSV format to be uploaded.</p>
    <p>You may find a copy of the <a href="Tagger CSV Upload Template User Instructions.docx">LRMI Template Guide</a> available online.This file contains the CSV file embedded.</p>
    <p>If you'd like more details on how the LRMI specification for each data field please see the appendix in the help file "importing resource data to create tags through bulk processing."</p>

    <form id="fileForm">
        <input type="file" id="files" name="files" multiple />
    </form>

    <hr/>
    <h4>Quick Load</h4>
    <p>To create multiple entries enter <i>title,URL</i> once per line.<br/>   <strong>Example:</strong><br/>  Actual Title,http://www.test.com<br/>Actual Title Two,http://www.test2.com</p>

    <textarea id="loadModalTextArea" style="height: 40px; width: 95%;font-size:small;"></textarea>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary" data-dismiss="modal" id="saveLoadModalButton">Load</a>
  </div>
</div>

app/views/tagger/modals/_message_modal.html.erb
<div id="messageModal" class="modal hide fade">
  <div class="modal-header">
    <a onclick="$('#messageModal').modal('hide'); return false;" class="close">&times;</a>
    <h3 class="header-text"></h3>
  </div>
  <div class="modal-body">
    <div class="body-text">

    </div>
  </div>
  <div class="modal-footer">
    <a onclick="$('#messageModal').modal('hide'); return false;" class="btn btn-success">OK</a>
  </div>
</div>

app/views/tagger/modals/_reset_modal.html.erb
<div id="resetModal" class="modal hide fade">
  <div class="modal-header">
    <a onclick="$('#resetModal').modal('hide'); return false;" class="close">&times;</a>
    <h3>Reset resource to draft state for editing?</h3>
  </div>
  <div class="modal-body">
    <p>You're about to reset this resource back to draft state for editing.</p>
    <p>Are you sure?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-success">Reset Resource</a>
    <a onclick="$('#resetModal').modal('hide'); return false;" class="btn">Cancel</a>
  </div>
</div>

app/views/tagger/modals/_thumbnail_modal.html.erb
<div class="modal hide fade" id="thumbModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" id="closeModalButton">X</button>
    <h3>Tag Image Uploader</h3>
  </div>
  <div class="modal-body">
    <p>Supported formats; jpg, gif and png.  Files should be no larger than 1.5megs.  Thumbnails will automatically be generated from the uploaded image.</p>
    <br/>

    <%= form_for Tag.new, :url => add_image_tagger_index_path, :html => { :id => 'thumbModalForm', :'data-type' => 'json', :remote => true, :multipart => true } do |f| %>
      <%= f.label :image, 'Choose Image File' %>
      <%= f.file_field :image %>
      <br />
    <% end %>
  </div>
  <div class="modal-footer">
    <a onclick="$('#thumbModalForm').submit(); $('#pleasewait').show(); return false;" class="btn btn-primary">Upload</a>
    <a onclick="$('#thumbModal').modal('hide'); return false;" class="btn btn-success">Close</a>
  </div>
</div>

app/views/tagger/modals/_wait_modal.html.erb
<div id="pleaseWaitModal" class="modal hide fade">
  <div class="modal-header">
    <h3 class="header-text">Please wait...</h3>
  </div>
  <div class="modal-body">
    <div class="body-text">

    </div>
  </div>
</div>